import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   manifest: "/manifest.json", // we are accessing our manifest file here
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  manifest: "/manifest.json",
  applicationName: "Farmour",
  title: {
    default: "Farmour - Friend of Farmer",
    template: "PWA Farmour - Friend of Farmer",
  },
  description: "Friend of Farmer",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Farmour - Friend of Farmer",
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: "Farmour - Friend of Farmer",
    title: {
      default: "Farmour - Friend of Farmer",
      template: "PWA Farmour - Friend of Farmer",
    },
    description: "Friend of Farmer",
  },
};

export const viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
